### ISSUE TITLE
Link individual item viewing page to the backend

### ISSUE THREAD

**Issue by HirdayGupta** [nikita1923666/TradeSpace#17]
![ind_item_ss](https://user-images.githubusercontent.com/18088721/69314231-7f0b8100-0be8-11ea-9b59-6beebe92a419.png)

^^ this screen currently displays only static content. The following two things need to happen:
- this screen needs to know the ID of the object its loading
- it should then  call the backend for info on the item and display that dynamic info. the api to use is: `GET /items/<ITEM_ID>` - it'll return an object with the following format 
```
{
id: String, 
title: String,
description: String,
location: String, 
owner_uid: String(user_id), 
photo_url: String, 
tags: [String]
}
```

**Comment by aadilio** [comment]
Need to have two options for this page: 1) Viewing a user's own item (should have Edit Item as the option) and 2) Have other items that are not of the users (currently does this I think)

**Comment by aadilio** [comment]
Did this through item.vue
