### ISSUE TITLE
Link "add item for trade" screen to backend

### ISSUE THREAD

**Issue by HirdayGupta** [nikita1923666/TradeSpace#19]
![add_item_ss](https://user-images.githubusercontent.com/18088721/69314835-f55cb300-0be9-11ea-8690-fe360253c964.png)

^^ this  screen.

Link it to the backend by calling `POST /items` when the user presses "SUBMIT". Format of the request is the same as the one described  in  #17

**Comment by aadilio** [comment]
Completed using `POST /items` but not exactly sure about what is meant by: "Format of the request is the same as the one described in #17." Pushed on master.

**Comment by HirdayGupta** [comment]
Yep the format is basically just this: 
```

{
id: String, 
title: String,
description: String,
location: String, 
owner_uid: String(user_id), 
photo_url: String, 
tags: [String]
}

```

**Comment by aadilio** [comment]
Are a photo and description supposed to be required when creating an item? Currently set as not required.

**Comment by aadilio** [comment]
Completed
