### ISSUE TITLE
Picture uploads on frontend (user profile & item) 

### ISSUE THREAD

**Issue by HirdayGupta** [nikita1923666/TradeSpace#22]
Use the firebase JS SDK to upload user profile image and item image to Firebase Storage. The Storage SDK will return a URL upon successful upload. Send this URL to the necessary APIs  for user/item creation as needed.

Here is some documentation on using the firebase API to talk to storage.
https://firebase.google.com/docs/storage/web/upload-files

**Comment by akaashvenkat** [comment]
To keep it standardized, have a folder per user. Set the folder name to the user's uid. Within that folder, have the user profile pic called "profile.jpg". And all items be called "<itemName>.jpg".

**Comment by akaashvenkat** [comment]
This needs to be implemented on 1) Sign Up page (for profile pic), 2) Add Item page, 3) Update Information page (for profile pic), 4) Edit Item page
